absolute_urls: false

home:
  alias: '/blog'

pages:
  theme: hpstr
  markdown_extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: true
